# Generated by Django 3.2.13 on 2022-06-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=30)),
                ('distance', models.CharField(max_length=30)),
                ('fair', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'add_fair',
            },
        ),
        migrations.CreateModel(
            name='AddStationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_image', models.ImageField(upload_to='station/')),
                ('station_name', models.CharField(max_length=30)),
                ('station_address', models.CharField(max_length=30)),
                ('platform_type', models.CharField(max_length=30)),
                ('distance', models.CharField(max_length=30)),
                ('number_1', models.BigIntegerField()),
                ('number_2', models.BigIntegerField()),
            ],
            options={
                'db_table': 'station_details',
            },
        ),
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin_login',
            },
        ),
    ]
