# Generated by Django 3.2.13 on 2022-06-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstationdetails',
            name='station_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addstationdetails',
            name='station_name',
            field=models.CharField(max_length=100),
        ),
    ]
