# Generated by Django 3.2.13 on 2022-06-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20220629_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstationdetails',
            name='number_1',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='addstationdetails',
            name='number_2',
            field=models.CharField(max_length=80),
        ),
    ]
