# Generated by Django 3.2.13 on 2022-06-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
