# Generated by Django 3.2.13 on 2022-06-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20220629_1350'),
        ('metro', '0003_auto_20220619_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookticket',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.addstationdetails'),
        ),
    ]
